### ISSUE TITLE
Do not use dynamic values

### ISSUE THREAD

**Issue by moltar** [gmournos/quicksight-as-code#1]
Hey George,

Got your ping from the CDK repo issue (https://github.com/aws/aws-cdk/issues/19212#issuecomment-1603747573)

Was looking at your code and so far it looks like a really in-depth solution and I am really enjoying studying your approach!

I have one recommendation though. Do not use dynamic (at build time) values like this. Because this will result in a d CloudFormation change, and will always result in an update, on every deployment.

https://github.com/gmournos/quicksight-as-code/blob/eae34b34663b3f06d1aab8d8fc8957ce011c7315/lib/constructs/qs-single-source-dataset-construct.ts#L122

**Comment by gmournos** [comment]
Thanks Roman,

I don't really use the refresh schedules. Partly also because it was impossible some time ago to use them with CDK. They have been added to Cloudformation-CDK roughly only a month ago. I just added them here to show that they are available now for those who need them. 

Very very good catch nonetheless, thank you very much. I guess I went too far into the suggestion I made in my article, "always consult the definition of the manually created dataset at every step". The manually created dataset will always set this to "next midnight" :)
