### ISSUE TITLE
Refresh using Step Function

### ISSUE THREAD

**Issue by moltar** [gmournos/quicksight-as-code#2]
Just a suggestion, nothing wrong with your solution. But a cool solution we developed is to use Step Functions to issue refresh requests. That way you don't need to maintain a Lambda and you get a nice visual log of all the runs, so don't need to even log into CloudWatch. Plus you can do retries, and even build a whole graph of refreshes, if you want, in the right sequence.

https://github.com/gmournos/quicksight-as-code/blob/eae34b34663b3f06d1aab8d8fc8957ce011c7315/lib/constructs/qs-extra-automation.ts#L102

**Comment by gmournos** [comment]
Hi Roman,

Once again thank you for your insightful comment.

Indeed, whatever can be done by a call from a lambda function, can also be done by a step in a state machine. Probably not only the refresh dataset step but also the update dataset permissions after the dataset creation. 

On the other side, it is a bit of a "potato - potatoe" situation :)

To be honest, I wanted to use lambda functions to showcase the use of the "new" (with v2) CDK construct NodejsFunction, because I often work with teams that do not know about it, and still package dependencies either by building custom layers or by using webpack. That is also why I wrote so relatively much in the article about NodejsFunction.

Since it is a "potato - potatoe" case, I will not change the lambda functions into step functions in the code.
I will, however, add a link to the article to this issue to inform readers that alternatively, lambda functions could be step functions.
